### ISSUE TITLE
Flexible width of <ul> in the 2nd level

### ISSUE THREAD

**Issue by leaunseld** [jbowyers/responsive-menu#3]
Hey there,

is it possible to have a flexible width of the ul elements in the 2nd level? In your demo they are fixed to 15em, for my purposes I removed this but then I got problems if the words in the 1st level are pretty short and in the 2nd level very long.

I tried by giving the affected ul a special width inside the element directly (though this is not a good but I guess a working solution) but it appears that the javascript removes every style before it sets its own.

Thanks in advance for your help!
Lea

**Comment by jbowyers** [comment]
did you try: 

`.rm-layout-expanded li ul, .rm-layout-expanded .rm-menu-item .rm-menu {
    width: auto;
}`

**Comment by leaunseld** [comment]
This helps and works perfectly!

I was trying to find this solution on my own and spent several hours on it, but wasn't able to fix it. So thanks a lot, you really helped me!

Lea

PS: I'm gonna remove the link above as I guess this post is stored for a long time.
